CREATE TABLE ACCOUNT (
  ACCOUNT_NUM     VARCHAR(10) PRIMARY KEY,
	ACCOUNT_TYPE    VARCHAR(50) NOT NULL,
	ACCOUNT_STATUS  VARCHAR(50) NOT NULL
);
INSERT INTO ACCOUNT VALUES ('10001', 'Savings Account', 'Active');
INSERT INTO ACCOUNT VALUES ('10002', 'Current Account', 'Dormant');
COMMIT;
